### PR TITLE
Agent Nodes [16569]

### PR DESCRIPTION
**Pull request by jparisu**
After 
- #58 

Todo:

- [ ] Code doxygen
- [x] Tests
- [ ] Manual testing in WAN
- [ ] Documentation

### CODE REVIEW

**Comment by rsanchez15** [comment]
Implementation and test LGTM

**Comment by jparisu** [comment]
This PR requires of https://github.com/eProsima/dev-utils/pull/35 to solve an ASAN problem

**Review by irenebm — APPROVED** [review]
LGTM

**Review by irenebm — APPROVED** [review]
LGTM

**Pull request merged**
